### ISSUE TITLE
Date field on 'add exam' doesn't accept browser date-picker formats

### ISSUE THREAD

**Issue by FrancisBehnen** [WISVCH/CHoice#23]
Temporary fix would be to make this a normal text field

**Comment by Fastjur** [comment]
It seems this issue is still somewhat persistent. It doesn't work on my machine. Attached a GIF of the issue.

When changing the date field we get a whitelabel error page, for a 400 bad request error:  
![Kapture 2019-05-15 at 12 12 02](https://user-images.githubusercontent.com/1493561/57767909-c7625780-770a-11e9-8b1b-359a4b6c9a98.gif)

When not changing the date field, the exam creation works fine:
![Kapture 2019-05-15 at 12 14 39](https://user-images.githubusercontent.com/1493561/57768091-2b851b80-770b-11e9-9a28-1d46d42ca6ec.gif)

**Comment by julian9499** [comment]
fixed in pull request #59
